/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nexfi_yuanpeigen_nexfi_android_ble_activity_ChatActivity_Myobserve */

#ifndef _Included_com_nexfi_yuanpeigen_nexfi_android_ble_activity_ChatActivity_Myobserve
#define _Included_com_nexfi_yuanpeigen_nexfi_android_ble_activity_ChatActivity_Myobserve
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
